language: java
jdk:
  - oraclejdk11
install: true
sudo: required
services:
  - docker
script: ./gradlew clean build -x signArchives -x uploadArchives --info
cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.gradle"
