# Set the base image to centos with java 8
FROM lwieske/java-8:jdk-8u45

################## BASE ####################################

RUN yum -y install git rpm-build wget tar unzip gzip nc tar unzip gzip libyaml
